Add Gitea indexation
octopusden/octopus-vcs-facade pull request #31
Opened 2024-04-10 12:27 UTC by CamaradeRoman

2024-04-10 14:42 UTC, ozonophore commented on client/src/main/kotlin/org/octopusden/octopus/vcsfacade/client/VcsFacadeRetry.kt
> +            log.debug("Retry: iteration={}, attempt={}", numberIterations - iteration + 1, numberAttempts - attempt + 1)
Тут не хватает проверки log.isDebugEnabled, чтоб исключить вычисление в режимах отличных от debug

2024-04-10 14:42 UTC, ozonophore commented on common/src/main/kotlin/org/octopusden/octopus/vcsfacade/client/common/dto/Ref.kt
> +        result = 31 * result + repository.hashCode()
Может это вычисление заменить на Objects.hash(type, name, commitId, link, repository)?

2024-04-10 21:03 UTC, CamaradeRoman commented on common/src/main/kotlin/org/octopusden/octopus/vcsfacade/client/common/dto/Ref.kt
> +        result = 31 * result + repository.hashCode()
Автосгенерированный IDEA метод. Особого смысла менять не вижу.

2024-04-10 21:05 UTC, CamaradeRoman commented on client/src/main/kotlin/org/octopusden/octopus/vcsfacade/client/VcsFacadeRetry.kt
> +            log.debug("Retry: iteration={}, attempt={}", numberIterations - iteration + 1, numberAttempts - attempt + 1)
Вычисление лог строки отдано на откуп фреймворку логирования, вычисления числа сложением/вычитанием примитивов кажется не слишком большим оверхедом.

2024-04-11 07:56 UTC, aryabokon requested changes

2024-04-11 07:56 UTC, aryabokon commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaIndexerServiceImpl.kt
> +    private val openSearchService: OpenSearchService?,
я против nullable в этом месте, в чем смысл?

2024-04-11 07:56 UTC, aryabokon commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaIndexerServiceImpl.kt
> +        giteaIndexScanExecutor?.submit {
совсем против

2024-04-11 07:56 UTC, aryabokon commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaService.kt
> -        private fun <T> execute(errorMessage: String, clientFunction: () -> T): T {
логика этого метода нужна для того, чтобы не пропускать NotFoundException клиента на хендлер, чтобы инкапсулировать клиента внутри сервиса, а выходит, чтобы выпилить Gitea, недостаточно выпилить его сервис и зависимость. При этом, ты во всех вызовах добавляешь .also. В чем реальный смысл этого изменения?

2024-04-11 07:56 UTC, aryabokon commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/controller/ExceptionInfoHandler.kt
> +    @ExceptionHandler(NotFoundException::class, GiteaNotFoundException::class, BitBucketNotFoundException::class)
я против добавления сюда клиентских исключений

2024-04-11 07:56 UTC, aryabokon commented on server/src/test/kotlin/org/octopusden/octopus/vcsfacade/vcs/RepositoryControllerBitbucketTest.kt
> +@EnabledIfSystemProperty(named = "test.profile", matches = "bitbucket")
@EnabledIf(value = "#{environment.getActiveProfiles()[0] == 'bitbucket'}", loadContext = true)

2024-04-11 07:56 UTC, aryabokon commented on server/src/test/resources/bootstrap-ut.yml
зачем тут профиль?

2024-04-11 08:12 UTC, CamaradeRoman commented on common/src/main/kotlin/org/octopusden/octopus/vcsfacade/client/common/dto/Commit.kt
> +data class Commit(
для совместимости есть класс RepositoryControllerOld.CommitOld

2024-04-11 08:14 UTC, CamaradeRoman commented on common/src/main/kotlin/org/octopusden/octopus/vcsfacade/client/common/exception/OtherException.kt
> +class OtherException(message: String) : VcsFacadeException(message)
VcsFacadeException был и остался абстрактным классом. Предоставляет удобный способ группировать всё VcsFacadeException разных типов.

2024-04-11 08:17 UTC, CamaradeRoman commented on .run/VCS Facade UT.run.xml
Переименовано в [VcsFacade (Development).run.xml](https://github.com/octopusden/octopus-vcs-facade/blob/add-vcs-indexation/.run/VcsFacade%20(Development).run.xml). Ничего общего с UT эта конфигурация не имела.

2024-04-11 08:20 UTC, CamaradeRoman commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/config/VCSConfig.kt
> +        if (token?.isNotBlank() == true) token else null,
Этот кусок я не менял вообще. Предложи варианты, как это должно быть, если текущий не устраивает.

2024-04-11 08:23 UTC, CamaradeRoman commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/document/Commit.kt
> +@ConditionalOnProperty(
При создании этого bean происходит создание или обновление opensearch index. Если интеграция с opensearch отключена, то делать это не требуется.

2024-04-11 08:26 UTC, CamaradeRoman commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaIndexerServiceImpl.kt
> +        giteaIndexScanExecutor?.submit {
Отличный коментарий. Совсем против чего?

В любом случае, фича по отключению через конфигурацию возможности проводить scan уже удалена.

2024-04-11 08:31 UTC, CamaradeRoman commented on server/src/test/kotlin/org/octopusden/octopus/vcsfacade/vcs/RepositoryControllerBitbucketTest.kt
> +@EnabledIfSystemProperty(named = "test.profile", matches = "bitbucket")
чем плох текущий вариант и чем лучше предлагаемый?

2024-04-11 08:36 UTC, CamaradeRoman commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaService.kt
> -        private fun <T> execute(errorMessage: String, clientFunction: () -> T): T {
Смысл не перевыбрасывать исключение (не пытаться клиентский not found подменить).

Я вообще не понимаю смысл упражнений вокруг только одного кейса с NotFoundException. Есть куча других возможных клиентских исключений, которые вылетают как есть. Почему это не нарушает желаемую инкапсуляцию по твоему мнению?

2024-04-11 08:37 UTC, CamaradeRoman commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaService.kt
> -        private fun <T> execute(errorMessage: String, clientFunction: () -> T): T {
Чтобы выпилить Gitea недостаточно убрать его сервис и зависимость в любом случае, не важно будет ли или нет использоваться подобный execute метод.

2024-04-11 08:38 UTC, CamaradeRoman commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/controller/GiteaIndexerController.kt
> +        if (eventType == "create" && event == "create") {
Не вижу особого смысла паковать две строки в pair. По производительности оба варианта не отличаются практически.

2024-04-11 08:42 UTC, CamaradeRoman commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaService.kt
> -        private fun <T> execute(errorMessage: String, clientFunction: () -> T): T {
Если потребуется на VCS manager уметь единообразно отслеживать и обрабатывать not found'ы от vcs сервисов - будет иметь смысл вернуться к подмене исключений. Пока этого не требуется я не вижу никакого смысла так делать.

2024-04-11 08:48 UTC, aryabokon commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/config/VCSConfig.kt
> +        if (token?.isNotBlank() == true) token else null,
я плохо прочитал что он делает, все тут ок

2024-04-11 08:50 UTC, aryabokon commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaService.kt
> -        private fun <T> execute(errorMessage: String, clientFunction: () -> T): T {
> Почему это не нарушает желаемую инкапсуляцию по твоему мнению?
потому, что они приезжают в секцию Exception::class и сервис отдает 500

> Я вообще не понимаю смысл упражнений вокруг только одного кейса с NotFoundException
потому, что это единственный вид, который мы понимаем

2024-04-11 08:52 UTC, aryabokon commented on server/src/test/kotlin/org/octopusden/octopus/vcsfacade/vcs/RepositoryControllerBitbucketTest.kt
> +@EnabledIfSystemProperty(named = "test.profile", matches = "bitbucket")
тем, что текущий вариант завязан на property, а мой - на профиль. Профиль может быть запущен не через property, а через @ActiveProfiles, что нативно поддерживает Idea на Run конфигурациях JUnit

2024-04-11 08:55 UTC, aryabokon commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/controller/ExceptionInfoHandler.kt
> +    @ExceptionHandler(NotFoundException::class, GiteaNotFoundException::class, BitBucketNotFoundException::class)
потому, что если будет сложносочиненная логика, где используется client.get..., мы попадем в 404, а может нам не нужно это и мы должны попасть в 500?

2024-04-11 10:30 UTC, aryabokon commented on common/src/main/kotlin/org/octopusden/octopus/vcsfacade/client/common/exception/OtherException.kt
> +class OtherException(message: String) : VcsFacadeException(message)
Почему бы его не сделать не абстрактным. Избежим лишнего класса

2024-04-11 11:00 UTC, aryabokon commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/controller/GiteaIndexerController.kt
> +        if (eventType == "create" && event == "create") {
визуально выглядит чище

2024-04-11 11:01 UTC, aryabokon commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaIndexerServiceImpl.kt
> +        giteaIndexScanExecutor?.submit {
выше был коммент
> я против nullable в этом месте

а ниже
> совсем против

2024-04-11 12:31 UTC, CamaradeRoman commented on common/src/main/kotlin/org/octopusden/octopus/vcsfacade/client/common/exception/OtherException.kt
> +class OtherException(message: String) : VcsFacadeException(message)
Сделал open вместо abstract.

2024-04-11 12:32 UTC, CamaradeRoman commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaService.kt
> -        private fun <T> execute(errorMessage: String, clientFunction: () -> T): T {
вот именно - понимаем, а теперь понимаем на хендлере без подмены

2024-04-11 13:11 UTC, CamaradeRoman commented on ft/docker/gitea/application-gitea.yml
> +opensearch:
Согласен, помувал. Осталось с момента попытки использовать auto-configuration.

2024-04-11 13:12 UTC, CamaradeRoman commented on server/src/main/kotlin/org/octopusden/octopus/vcsfacade/service/impl/GiteaIndexerServiceImpl.kt
> +    private val openSearchService: OpenSearchService?,
Усложнил conditional check, убрал nullable.

2024-04-11 14:10 UTC, CamaradeRoman commented on server/src/test/kotlin/org/octopusden/octopus/vcsfacade/vcs/RepositoryControllerBitbucketTest.kt
> +@EnabledIfSystemProperty(named = "test.profile", matches = "bitbucket")
Я заменил проверку system property на анализ активных профилей, но мне кажется что стало хуже читаемо (а еще - неединообразно с FT).

@EnabledIf("#{environment.getActiveProfiles().$[#this == 'gitea'] == 'gitea'}", loadContext = true)

2024-04-12 07:40 UTC, ozonophore approved these changes

2024-04-12 08:04 UTC, pgorbachev approved these changes
FT on JDK 21 passed

2024-04-12 08:10 UTC, merged